# coding: utf-8

"""
xButler webserver

Web server for ML services of xButler

The version of the OpenAPI document: 1.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from src import config
from src.apis import ResourceRouter, RetrievalRouter

app = FastAPI(
    title="xButler webserver",
    description="Web server for ML services of xButler",
    version="1.1.0",
)

app.add_middleware(
    CORSMiddleware, allow_origins=["*"], allow_credentials=True, allow_methods=["*"], allow_headers=["*"]
)

api_version = f"/{config.API_VERSION}"
app.include_router(ResourceRouter, prefix=api_version)
app.include_router(RetrievalRouter, prefix=api_version)
